import { ObjectSchema, versionSchemas } from "@cypress/schema-tools";

const Response1: ObjectSchema = {
  version: {
    major: 3,
    minor: 0,
    patch: 0,
  },
  schema: {
    title: "response",
    type: "object",
    properties: {
      thief: {
        type: "object",
        properties: {
          weapon: { type: "string" },
          upgradedWeapon: { type: "string" },
          armor: { type: "string" },
          upgradedArmor: { type: "string" },
          strength: { type: "number" },
          agility: { type: "number" },
          wisdom: { type: "number" },
          magic: { type: "number" },
        },
        required: [
          "weapon",
          "upgradedWeapon",
          "armor",
          "upgradedArmor",
          "strength",
          "agility",
          "wisdom",
          "magic",
        ],
        additionalProperties: false,
      },
      knight: {
        type: "object",
        properties: {
          weapon: { type: "string" },
          upgradedWeapon: { type: "string" },
          armor: { type: "string" },
          upgradedArmor: { type: "string" },
          strength: { type: "number" },
          agility: { type: "number" },
          wisdom: { type: "number" },
          magic: { type: "number" },
        },
        required: [
          "weapon",
          "upgradedWeapon",
          "armor",
          "upgradedArmor",
          "strength",
          "agility",
          "wisdom",
          "magic",
        ],
        additionalProperties: false,
      },
      mage: {
        type: "object",
        properties: {
          weapon: { type: "string" },
          upgradedWeapon: { type: "string" },
          armor: { type: "string" },
          upgradedArmor: { type: "string" },
          strength: { type: "number" },
          agility: { type: "number" },
          wisdom: { type: "number" },
          magic: { type: "number" },
        },
        required: [
          "weapon",
          "upgradedWeapon",
          "armor",
          "upgradedArmor",
          "strength",
          "agility",
          "wisdom",
          "magic",
        ],
      },
      brigadier: {
        type: "object",
        properties: {
          weapon: { type: "string" },
          upgradedWeapon: { type: "string" },
          armor: { type: "string" },
          upgradedArmor: { type: "string" },
          strength: { type: "number" },
          agility: { type: "number" },
          wisdom: { type: "number" },
          magic: { type: "number" },
        },
        required: [
          "weapon",
          "upgradedWeapon",
          "armor",
          "upgradedArmor",
          "strength",
          "agility",
          "wisdom",
          "magic",
        ],
        additionalProperties: false,
      },
    },
    required: ["thief", "knight", "mage", "brigadier"],
    additionalProperties: false,
  },
  example: {},
};

export const Response = versionSchemas(Response1);
